spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devmate?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update   # 개발 단계는 update, 운영은 validate 권장
    properties:
      hibernate:
        format_sql: true
#        show_sql: true
        jdbc.time_zone: UTC
#        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: never               # schema.sql/data.sql 자동실행 제어 (always/embedded/never)
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            scope: openid, email, profile
          github:
            client-id: ${GITHUB_CLIENT_ID:}
            client-secret: ${GITHUB_CLIENT_SECRET:}
            scope: user:email
  jackson:
    time-zone: UTC

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

  # 비밀키는 엄격히 관리하자...