services:
  redis:
    image: redis:7.4-alpine
    ports: [ "6379:6379" ]
    container_name: devmate-redis
    restart: unless-stopped
    command: ["redis-server","--appendonly","yes"]

    #    실행은 docker compose up -d redis (또는 docker-compose up -d redis)
    #
    #    정상 동작 확인:  docker exec -it devmate-redis redis-cli ping → PONG